# todo: setup postgres db
sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 6
  - 5
  - 4
  - '0.10'
services:
  - postgresql
env:
  - PG_CONNECTION_STRING="postgres://postgres@localhost/travis_ci_test"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
