dbcreate:
  image: postgres:9.3
  external_links:
    - blockai_postgres_1:db
  command: >
    /bin/bash -c "
      while ! psql --host=db --username=postgres; do sleep 1; done;
      psql --host=db --username=postgres -c 'DROP DATABASE \"advisorylock\";';
      psql --host=db --username=postgres -c 'CREATE DATABASE \"advisorylock\";';
    "
